# Generated by Django 4.0.3 on 2022-04-20 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': "Ko'p so'raladigan savol ", 'verbose_name_plural': "Ko'p so'raladigan savollar"},
        ),
    ]
