# Generated by Django 4.0.3 on 2022-04-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_alter_faq_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(null=True, verbose_name='Javob:'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(null=True, verbose_name='Javob:'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_uz',
            field=models.TextField(null=True, verbose_name='Javob:'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_uzb',
            field=models.TextField(null=True, verbose_name='Javob:'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Savol:'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Savol:'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_uz',
            field=models.CharField(max_length=500, null=True, verbose_name='Savol:'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_uzb',
            field=models.CharField(max_length=500, null=True, verbose_name='Savol:'),
        ),
    ]
