# Generated by Django 4.0.3 on 2022-04-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_faq_answer_en_faq_answer_ru_faq_answer_uz_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['index'], 'verbose_name': "Ko'p so'raladigan savol ", 'verbose_name_plural': "Ko'p so'raladigan savollar"},
        ),
        migrations.AddField(
            model_name='faq',
            name='index',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tartib raqaqmi'),
        ),
    ]
