# Generated by Django 4.0.3 on 2022-03-31 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useful_link', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usefullink',
            options={'verbose_name': 'Foydali havola ', 'verbose_name_plural': 'Foydali havolalar'},
        ),
        migrations.AddField(
            model_name='usefullink',
            name='title_en',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='usefullink',
            name='title_ru',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='usefullink',
            name='title_uz',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='usefullink',
            name='title_uzb',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Title'),
        ),
    ]
