# Generated by Django 4.0.3 on 2022-04-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useful_link', '0002_alter_usefullink_options_usefullink_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usefullink',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Aktiv'),
        ),
    ]
