# Generated by Django 4.0.3 on 2022-04-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useful_link', '0003_usefullink_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usefullink',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Aktiv'),
        ),
    ]
