# Generated by Django 4.0.3 on 2022-04-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useful_link', '0005_alter_usefullink_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usefullink',
            options={'ordering': ['-index'], 'verbose_name': 'Foydali havola ', 'verbose_name_plural': 'Foydali havolalar'},
        ),
        migrations.AddField(
            model_name='usefullink',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
