# Generated by Django 4.0.3 on 2022-04-21 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useful_link', '0006_alter_usefullink_options_usefullink_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usefullink',
            options={'ordering': ['index'], 'verbose_name': 'Foydali havola ', 'verbose_name_plural': 'Foydali havolalar'},
        ),
    ]
