# Generated by Django 4.0.3 on 2022-04-13 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0007_alter_menu_options_menu_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('title', models.CharField(max_length=500, verbose_name='Mavzu')),
                ('title_uz', models.CharField(max_length=500, null=True, verbose_name='Mavzu')),
                ('title_uzb', models.CharField(max_length=500, null=True, verbose_name='Mavzu')),
                ('title_ru', models.CharField(max_length=500, null=True, verbose_name='Mavzu')),
                ('title_en', models.CharField(max_length=500, null=True, verbose_name='Mavzu')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Matni')),
                ('content_uz', models.TextField(blank=True, null=True, verbose_name='Matni')),
                ('content_uzb', models.TextField(blank=True, null=True, verbose_name='Matni')),
                ('content_ru', models.TextField(blank=True, null=True, verbose_name='Matni')),
                ('content_en', models.TextField(blank=True, null=True, verbose_name='Matni')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='post', verbose_name='Asosiy rasm')),
                ('views', models.IntegerField(blank=True, default=0, null=True, verbose_name="Ko'rishlar Soni")),
                ('pub_date', models.DateTimeField(verbose_name='Sanasi')),
                ('on_slider', models.BooleanField(blank=True, default=0, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='menu.menu', verbose_name='Menyu')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Postlar',
                'db_table': 'post',
                'ordering': ['-pub_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('name', models.CharField(max_length=255, verbose_name='Teg nomi')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Teg nomi')),
                ('name_uzb', models.CharField(max_length=255, null=True, verbose_name='Teg nomi')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Teg nomi')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Teg nomi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teg',
                'verbose_name_plural': 'Teglar',
                'db_table': 'post_tag',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='PostImages', verbose_name='Foto')),
                ('is_active', models.BooleanField(blank=True, default=False, null=True, verbose_name='Aktiv')),
                ('index', models.IntegerField(blank=True, null=True, verbose_name='Tartib raqami')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='post.post', verbose_name='Rasmlar')),
            ],
            options={
                'db_table': 'post_images',
                'ordering': ['index'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='post.tags', verbose_name='Teglar'),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
