# Generated by Django 4.0.3 on 2022-04-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(verbose_name='Sanasi'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_uz',
            field=models.CharField(max_length=500, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_uzb',
            field=models.CharField(max_length=500, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='postimages',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
    ]
