# Generated by Django 4.0.3 on 2022-04-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_pub_date_alter_post_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='on_slider',
            field=models.BooleanField(default=False),
        ),
    ]
