# Generated by Django 4.0.3 on 2022-05-06 05:01

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_on_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=post.models.image_dir, verbose_name='Fayl'),
        ),
    ]
