# Generated by Django 4.0.3 on 2022-05-07 04:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_remove_post_file_postattachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Sanasi'),
        ),
    ]
