# Generated by Django 4.0.3 on 2022-05-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_post_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='postattachments',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='postattachments',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='postattachments',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='postattachments',
            name='name_uzb',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
    ]
