# Generated by Django 3.2.4 on 2022-05-11 11:45

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_postattachments_name_en_postattachments_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postattachments',
            name='file_en',
            field=models.FileField(null=True, upload_to=post.models.attach_dir, verbose_name='Fayl'),
        ),
        migrations.AddField(
            model_name='postattachments',
            name='file_ru',
            field=models.FileField(null=True, upload_to=post.models.attach_dir, verbose_name='Fayl'),
        ),
        migrations.AddField(
            model_name='postattachments',
            name='file_uz',
            field=models.FileField(null=True, upload_to=post.models.attach_dir, verbose_name='Fayl'),
        ),
        migrations.AddField(
            model_name='postattachments',
            name='file_uzb',
            field=models.FileField(null=True, upload_to=post.models.attach_dir, verbose_name='Fayl'),
        ),
    ]
