# Generated by Django 4.0.3 on 2022-05-19 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_remove_post_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postattachments',
            options={'verbose_name': 'Post fayllari', 'verbose_name_plural': 'Postlar fayllari'},
        ),
        migrations.AlterModelTable(
            name='postattachments',
            table='post_attachments',
        ),
    ]
