# Generated by Django 4.0.3 on 2022-05-26 14:43

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_alter_menu_options'),
        ('post', '0011_alter_post_photo_alter_postimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='menu',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='menu.menu', verbose_name='Menyu'),
        ),
    ]
