# Generated by Django 4.0.3 on 2022-05-31 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_alter_post_menu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
