# Generated by Django 4.0.3 on 2022-04-07 12:32

import config.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiogallery',
            name='name_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Gallariya nomi'),
        ),
        migrations.AddField(
            model_name='audiogallery',
            name='name_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Gallariya nomi'),
        ),
        migrations.AddField(
            model_name='audiogallery',
            name='name_uz',
            field=models.CharField(max_length=500, null=True, verbose_name='Gallariya nomi'),
        ),
        migrations.AddField(
            model_name='audiogallery',
            name='name_uzb',
            field=models.CharField(max_length=500, null=True, verbose_name='Gallariya nomi'),
        ),
        migrations.AddField(
            model_name='photogallery',
            name='name_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Gallariya nomi'),
        ),
        migrations.AddField(
            model_name='photogallery',
            name='name_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Gallariya nomi'),
        ),
        migrations.AddField(
            model_name='photogallery',
            name='name_uz',
            field=models.CharField(max_length=500, null=True, verbose_name='Gallariya nomi'),
        ),
        migrations.AddField(
            model_name='photogallery',
            name='name_uzb',
            field=models.CharField(max_length=500, null=True, verbose_name='Gallariya nomi'),
        ),
        migrations.AddField(
            model_name='videogallery',
            name='name_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Gallariya nomi'),
        ),
        migrations.AddField(
            model_name='videogallery',
            name='name_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Gallariya nomi'),
        ),
        migrations.AddField(
            model_name='videogallery',
            name='name_uz',
            field=models.CharField(max_length=500, null=True, verbose_name='Gallariya nomi'),
        ),
        migrations.AddField(
            model_name='videogallery',
            name='name_uzb',
            field=models.CharField(max_length=500, null=True, verbose_name='Gallariya nomi'),
        ),
        migrations.AlterField(
            model_name='audiogallery',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='AudioGallery', validators=[config.validation.validate_audio], verbose_name='Audio fayl'),
        ),
    ]
