# Generated by Django 4.0.3 on 2022-04-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_audiogallery_name_en_audiogallery_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogallerylink',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='videogallerylink',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='videogallerylink',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='videogallery',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Havola'),
        ),
        migrations.DeleteModel(
            name='AudioGallery',
        ),
        migrations.DeleteModel(
            name='VideoGalleryLink',
        ),
    ]
