# Generated by Django 4.0.3 on 2022-04-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_remove_videogallerylink_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photogallery',
            options={'verbose_name': 'Foto galereya', 'verbose_name_plural': 'Foto galereyalar'},
        ),
        migrations.AlterModelOptions(
            name='videogallery',
            options={'verbose_name': 'Video Galereya', 'verbose_name_plural': 'Video Galereyalar'},
        ),
        migrations.AddField(
            model_name='photogallery',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Aktiv'),
        ),
        migrations.AddField(
            model_name='videogallery',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Aktiv'),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Galereya nomi'),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='name_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Galereya nomi'),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='name_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Galereya nomi'),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='name_uz',
            field=models.CharField(max_length=500, null=True, verbose_name='Galereya nomi'),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='name_uzb',
            field=models.CharField(max_length=500, null=True, verbose_name='Galereya nomi'),
        ),
        migrations.AlterField(
            model_name='videogallery',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Galereya nomi'),
        ),
        migrations.AlterField(
            model_name='videogallery',
            name='name_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Galereya nomi'),
        ),
        migrations.AlterField(
            model_name='videogallery',
            name='name_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Galereya nomi'),
        ),
        migrations.AlterField(
            model_name='videogallery',
            name='name_uz',
            field=models.CharField(max_length=500, null=True, verbose_name='Galereya nomi'),
        ),
        migrations.AlterField(
            model_name='videogallery',
            name='name_uzb',
            field=models.CharField(max_length=500, null=True, verbose_name='Galereya nomi'),
        ),
    ]
