# Generated by Django 4.0.3 on 2022-04-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_photogallery_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photogallery',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
        migrations.AlterField(
            model_name='videogallery',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
    ]
