# Generated by Django 4.0.3 on 2022-04-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_photogallery_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photogallery',
            name='on_slider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videogallery',
            name='on_slider',
            field=models.BooleanField(default=False),
        ),
    ]
