# Generated by Django 4.0.3 on 2022-04-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_photogallery_on_slider_videogallery_on_slider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photogallery',
            options={'ordering': ['index'], 'verbose_name': 'Foto galereya', 'verbose_name_plural': 'Foto galereyalar'},
        ),
        migrations.AlterModelOptions(
            name='videogallery',
            options={'ordering': ['index'], 'verbose_name': 'Video Galereya', 'verbose_name_plural': 'Video Galereyalar'},
        ),
        migrations.AddField(
            model_name='photogallery',
            name='index',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tartib raqami'),
        ),
        migrations.AddField(
            model_name='videogallery',
            name='index',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tartib raqami'),
        ),
    ]
