# Generated by Django 4.0.3 on 2022-04-29 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_alter_photogallery_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photogallery',
            options={'ordering': ['-index'], 'verbose_name': 'Foto galereya', 'verbose_name_plural': 'Foto galereyalar'},
        ),
        migrations.AlterModelOptions(
            name='videogallery',
            options={'ordering': ['-index'], 'verbose_name': 'Video Galereya', 'verbose_name_plural': 'Video Galereyalar'},
        ),
    ]
