# Generated by Django 3.2.4 on 2022-05-11 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_alter_photogallery_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videogallery',
            options={'ordering': ['-index'], 'verbose_name': 'Video galereya', 'verbose_name_plural': 'Video galereyalar'},
        ),
    ]
