# Generated by Django 4.0.3 on 2022-04-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200, verbose_name='F.I.SH.')),
                ('phone', models.CharField(max_length=13, verbose_name='Telefon Raqami')),
                ('region', models.CharField(choices=[('andijon', 'Andijon viloyati'), ('buxoro', 'Buxoro viloyati'), ('jizzax', 'Jizzax viloyati'), ('qashqadaryo', 'Qashqadaryo viloyati'), ('navoiy', 'Navoiy viloyati'), ('namangan', 'Namangan viloyati'), ('samarqand', 'Samarqand viloyati'), ('surxondaryo', 'Surxondaryo viloyati'), ('sirdaryo', 'Sirdaryo viloyati'), ('toshkent', 'Toshkent viloyati'), ('fargona', 'Fargʻona viloyati'), ('xorazm', 'Xorazm viloyati'), ('qoraqalpogiston', 'Qoraqalpogʻiston Respublikasi'), ('toshkentsh', 'Toshkent shahar')], max_length=100, verbose_name='Hududi')),
                ('address', models.CharField(max_length=200, verbose_name='Manzil')),
                ('file', models.FileField(blank=True, null=True, upload_to='ContactFiles', verbose_name='Faylni Yuklang')),
                ('mail', models.EmailField(max_length=254, verbose_name='Elektron Pochta')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratildi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirildi")),
                ('status', models.IntegerField(choices=[(0, 'Yangi'), (1, 'Qabul Qilingan'), (2, 'Qaytarilgan'), (3, 'Ruhsat Berilgan')], default=0, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Murojat',
                'verbose_name_plural': 'Murojatlar',
                'db_table': 'contact',
            },
        ),
    ]
