# Generated by Django 4.0.3 on 2022-04-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='reply',
            field=models.TextField(blank=True, null=True, verbose_name='Admin Javobi'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.IntegerField(choices=[(0, 'Yangi'), (1, 'Qabul Qilingan'), (2, 'Rad Etilgan'), (3, 'Tasdiqlangan')], default=0, verbose_name='Status'),
        ),
    ]
