# Generated by Django 4.0.3 on 2022-04-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_reply_alter_contact_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.IntegerField(choices=[(0, 'Yangi'), (1, 'Qabul Qilingan'), (2, 'Rad Etilgan')], default=0, verbose_name='Status'),
        ),
    ]
