# Generated by Django 4.0.3 on 2022-05-19 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20220511_1509'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='appeal',
        ),
    ]
