# Generated by Django 4.0.3 on 2022-05-17 13:21

from django.db import migrations, models
import django.db.models.deletion
import internshipcosts.models


class Migration(migrations.Migration):

    dependencies = [
        ('internshipcosts', '0002_alter_internuser_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialreport',
            name='internship_expenses',
        ),
        migrations.AddField(
            model_name='financialreport',
            name='intern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internshipcosts.internuser'),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='file',
            field=models.FileField(upload_to=internshipcosts.models.finance_report_directory, verbose_name='Hisobot'),
        ),
    ]
