# Generated by Django 4.0.3 on 2022-05-18 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('internshipcosts', '0003_remove_financialreport_internship_expenses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intern', to=settings.AUTH_USER_MODEL),
        ),
    ]
