# Generated by Django 4.0.3 on 2022-05-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internshipcosts', '0004_alter_internuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialreport',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Yangi'), (2, 'Qabul qilindi'), (3, 'Rad etildi')], default=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='internshipexpenses',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Yangi'), (2, 'Qabul qilindi'), (3, 'Rad etildi')], default=1, verbose_name='Status'),
        ),
    ]
