# Generated by Django 4.0.3 on 2022-05-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internshipcosts', '0005_financialreport_status_internshipexpenses_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='internuser',
            name='reset_code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Tiklash kodi'),
        ),
    ]
