# Generated by Django 4.0.3 on 2022-05-20 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internshipcosts', '0006_internuser_reset_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostStatementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Xarajatlar asosnomasi turi',
                'verbose_name_plural': 'Xarajatlar asosnomasi turlari',
                'db_table': 'internship_cost_statement_type',
            },
        ),
        migrations.RemoveField(
            model_name='coststatement',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='coststatement',
            name='start_date',
        ),
        migrations.AddField(
            model_name='coststatement',
            name='currency',
            field=models.CharField(default='UZ', max_length=10, verbose_name='Valyuta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coststatement',
            name='days',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kunlar soni'),
        ),
        migrations.AlterField(
            model_name='coststatement',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='internshipcosts.coststatementtype', verbose_name='Xarajat turi'),
        ),
    ]
