# Generated by Django 4.0.3 on 2022-05-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internshipcosts', '0007_coststatementtype_remove_coststatement_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coststatementtype',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='coststatementtype',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='coststatementtype',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='coststatementtype',
            name='name_uzb',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
    ]
