# Generated by Django 4.0.3 on 2022-05-23 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internshipcosts', '0008_coststatementtype_name_en_coststatementtype_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coststatement',
            name='cost',
            field=models.BigIntegerField(verbose_name='Summasi'),
        ),
        migrations.AlterField(
            model_name='coststatement',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='intern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internshipcosts.internuser', verbose_name='Stajor'),
        ),
        migrations.AlterField(
            model_name='internshipexpenses',
            name='intern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internshipcosts.internuser', verbose_name='Stajor'),
        ),
    ]
