# Generated by Django 4.0.3 on 2022-05-25 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('internshipcosts', '0009_alter_coststatement_cost_alter_coststatement_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipCostsInfo',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('cost_statement', models.FileField(upload_to='internship/templates', verbose_name='Xarajatlar asosnomasi namunasi')),
                ('cost_statement_uz', models.FileField(null=True, upload_to='internship/templates', verbose_name='Xarajatlar asosnomasi namunasi')),
                ('cost_statement_uzb', models.FileField(null=True, upload_to='internship/templates', verbose_name='Xarajatlar asosnomasi namunasi')),
                ('cost_statement_ru', models.FileField(null=True, upload_to='internship/templates', verbose_name='Xarajatlar asosnomasi namunasi')),
                ('cost_statement_en', models.FileField(null=True, upload_to='internship/templates', verbose_name='Xarajatlar asosnomasi namunasi')),
                ('financial_report', models.FileField(upload_to='internship/templates', verbose_name='Moliyaviy hisobot namunasi')),
                ('financial_report_uz', models.FileField(null=True, upload_to='internship/templates', verbose_name='Moliyaviy hisobot namunasi')),
                ('financial_report_uzb', models.FileField(null=True, upload_to='internship/templates', verbose_name='Moliyaviy hisobot namunasi')),
                ('financial_report_ru', models.FileField(null=True, upload_to='internship/templates', verbose_name='Moliyaviy hisobot namunasi')),
                ('financial_report_en', models.FileField(null=True, upload_to='internship/templates', verbose_name='Moliyaviy hisobot namunasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hisobotlar namunasi',
                'verbose_name_plural': 'Hisobotlar namunasi',
                'db_table': 'internship_costs_info',
            },
        ),
    ]
