# Generated by Django 4.0.3 on 2022-04-14 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0006_vacancy_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='body',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='body_en',
            new_name='content_en',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='body_ru',
            new_name='content_ru',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='body_uz',
            new_name='content_uz',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='body_uzb',
            new_name='content_uzb',
        ),
    ]
