# Generated by Django 4.0.3 on 2022-04-26 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('title', models.CharField(max_length=255, verbose_name='Mavzusi')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Mavzusi')),
                ('title_uzb', models.CharField(max_length=255, null=True, verbose_name='Mavzusi')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Mavzusi')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Mavzusi')),
                ('content', models.TextField(verbose_name='Mazmuni')),
                ('content_uz', models.TextField(null=True, verbose_name='Mazmuni')),
                ('content_uzb', models.TextField(null=True, verbose_name='Mazmuni')),
                ('content_ru', models.TextField(null=True, verbose_name='Mazmuni')),
                ('content_en', models.TextField(null=True, verbose_name='Mazmuni')),
                ('start_time', models.DateTimeField(verbose_name='Boshlanish vaqti')),
                ('end_time', models.DateTimeField(verbose_name='Tugash vaqti')),
                ('responsible_org', models.CharField(max_length=255, verbose_name="Mas'ul tashkilot")),
                ('address', models.CharField(max_length=255, verbose_name='Manzili')),
                ('pub_date', models.DateField(verbose_name="E'lon Sanasi")),
                ('views', models.IntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('on_slider', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tadbir',
                'verbose_name_plural': 'Tadbirlar',
                'db_table': 'event',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nomi')),
                ('name_uz', models.CharField(max_length=300, null=True, verbose_name='Nomi')),
                ('name_uzb', models.CharField(max_length=300, null=True, verbose_name='Nomi')),
                ('name_ru', models.CharField(max_length=300, null=True, verbose_name='Nomi')),
                ('name_en', models.CharField(max_length=300, null=True, verbose_name='Nomi')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Tadbir Turi',
                'verbose_name_plural': 'Tadbir Turlari',
                'db_table': 'event_type',
            },
        ),
        migrations.CreateModel(
            name='EventImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='EventImages', verbose_name='Rasm')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='event.event')),
            ],
            options={
                'verbose_name': 'Tadbir Rasmi',
                'verbose_name_plural': 'Tadbir Rasmlari',
                'db_table': 'event_images',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.eventtype', verbose_name='Tadbir turi'),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
