# Generated by Django 4.0.3 on 2022-05-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Manzili'),
        ),
        migrations.AddField(
            model_name='event',
            name='address_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Manzili'),
        ),
        migrations.AddField(
            model_name='event',
            name='address_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Manzili'),
        ),
        migrations.AddField(
            model_name='event',
            name='address_uzb',
            field=models.CharField(max_length=255, null=True, verbose_name='Manzili'),
        ),
        migrations.AddField(
            model_name='event',
            name='main_topic',
            field=models.TextField(default='main topic', verbose_name='Asosiy mazmuni'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='main_topic_en',
            field=models.TextField(null=True, verbose_name='Asosiy mazmuni'),
        ),
        migrations.AddField(
            model_name='event',
            name='main_topic_ru',
            field=models.TextField(null=True, verbose_name='Asosiy mazmuni'),
        ),
        migrations.AddField(
            model_name='event',
            name='main_topic_uz',
            field=models.TextField(null=True, verbose_name='Asosiy mazmuni'),
        ),
        migrations.AddField(
            model_name='event',
            name='main_topic_uzb',
            field=models.TextField(null=True, verbose_name='Asosiy mazmuni'),
        ),
        migrations.AddField(
            model_name='event',
            name='responsible_org_en',
            field=models.CharField(max_length=255, null=True, verbose_name="Mas'ul tashkilot"),
        ),
        migrations.AddField(
            model_name='event',
            name='responsible_org_ru',
            field=models.CharField(max_length=255, null=True, verbose_name="Mas'ul tashkilot"),
        ),
        migrations.AddField(
            model_name='event',
            name='responsible_org_uz',
            field=models.CharField(max_length=255, null=True, verbose_name="Mas'ul tashkilot"),
        ),
        migrations.AddField(
            model_name='event',
            name='responsible_org_uzb',
            field=models.CharField(max_length=255, null=True, verbose_name="Mas'ul tashkilot"),
        ),
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.TextField(verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content_uz',
            field=models.TextField(null=True, verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content_uzb',
            field=models.TextField(null=True, verbose_name='Matn'),
        ),
    ]
