# Generated by Django 4.0.3 on 2022-05-05 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_address_en_event_address_ru_event_address_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='on_slider',
        ),
        migrations.AlterField(
            model_name='event',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name="Ko'rishlar soni"),
        ),
    ]
