# Generated by Django 4.0.3 on 2022-05-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_remove_event_on_slider_alter_event_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.TextField(verbose_name='Matni'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Matni'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Matni'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content_uz',
            field=models.TextField(null=True, verbose_name='Matni'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content_uzb',
            field=models.TextField(null=True, verbose_name='Matni'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pub_date',
            field=models.DateField(blank=True, null=True, verbose_name="E'lon Sanasi"),
        ),
        migrations.AlterField(
            model_name='event',
            name='views',
            field=models.IntegerField(default=0, verbose_name="Ko'rishlar soni"),
        ),
    ]
