# Generated by Django 3.2.4 on 2022-05-11 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_event_content_alter_event_content_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtype',
            options={'verbose_name': 'Tadbir turi', 'verbose_name_plural': 'Tadbir turlari'},
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='event',
            name='address_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='event',
            name='address_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='event',
            name='address_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='event',
            name='address_uzb',
            field=models.CharField(max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.TextField(verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content_uz',
            field=models.TextField(null=True, verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content_uzb',
            field=models.TextField(null=True, verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Mavzu'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Mavzu'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Mavzu'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Mavzu'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_uzb',
            field=models.CharField(max_length=255, null=True, verbose_name='Mavzu'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.eventtype', verbose_name='Tadbir tur'),
        ),
    ]
