from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.CountryListView.as_view()),
    path('finance-internship/', include('statisticsapp.finance_internship.urls')),
    path('countries', views.CountryList.as_view(), name="countries"),
    path('regions', views.RegionsList.as_view(), name="regions"),
    path('science-fields', views.ScienceFieldListView.as_view(), name="science-fields"),
    path('financing-entities', views.FinanceEntityList.as_view()),
    path('intern-count', views.InternCountListView.as_view()),
    path('annual-count-types', views.AnnualCostListView.as_view()),
    path('mainpagestatistics', views.YoungScientistInternshipListView.as_view()),
    path('regions/statistics', views.RegionStatListView.as_view(), name="regions"),
    path('regions/all', views.RegionStatisticsListView.as_view()),
    path('regions/<name>/', views.RegionDetailView.as_view()),
    path('<code>/', views.CountryDetailView.as_view()),
    path('financing-entities/<type>/', views.FinanceEntityByType.as_view()),
    path('region-sights/regions/', views.RegionSightHasListView.as_view()),
    path('region-sights/<region>/', views.RegionSightListView.as_view()),
    path('region-sights/<slug>', views.RegionSightDetailView.as_view()),
    path('count/gallery', views.CountFotoAndVideoView.as_view()),
    path('count/post/year', views.CountPostByYearView.as_view()),
    path('count/post/month', views.CountPostByMonthView.as_view()),
    path('count/post/day', views.CountPostByDayView.as_view()),
    path('count/normative-documents/day', views.NormativeDocumentByDayView.as_view()),
    path('count/normative-documents/month', views.NormativeDocumentMonthView.as_view()),
    path('count/normative-documents/year', views.NormativeDocumentYearView.as_view()),
    # path('scientific/internship/', views.ScientificInternshipYearsView.as_view()),
    path('scientific/internship/all-years', views.ScientificInternshipAllView.as_view()),
    path('scientific/internship/years', views.ScientificInternshipYearsView.as_view()),
    path('scientific/internship/years/<year>', views.ScientificInternshipByYearView.as_view()),
    path('scientific/internship/all/<type>', views.ScientificInternshipView.as_view()),
    path('scientific/internship/region', views.ScientificInternshipRegionListView.as_view()),
    path('scientific/internship/<region>', views.ScientificInternshipDetailByRegionView.as_view()),
    path('scientific/internship/<region>/years', views.ScientificInternshipByRegionYearsView.as_view()),
    path('scientific/internship/<region>/<year>', views.ScientificInternshipDetailByRegionYearView.as_view()),
    path('appeal/by-applicant', views.AppealStatisticsByApplicantView.as_view()),
    path('appeal/by-status', views.AppealStatisticsByStatusView.as_view()),
    path('appeal/by-quarter', views.AppealQuarterStatisticsView.as_view()),
    path('equipments', views.EquipmentPurchaseStatisticsView.as_view()),
]

