# Generated by Django 4.0.3 on 2022-04-04 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name="To'liq ism ")),
                ('position', models.CharField(blank=True, max_length=500, null=True, verbose_name='Lavozimi ')),
                ('internship', models.CharField(blank=True, max_length=500, null=True, verbose_name='Amaliyot joyi va muddati ')),
                ('phone', models.PositiveSmallIntegerField(blank=True, max_length=12, null=True, verbose_name='Telefon raqam ')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True, verbose_name='Elektron pochta manzil ')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Amaliyotchi haqida ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='internship/images/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Amaliyotchi',
                'verbose_name_plural': 'Amaliyotchilar',
                'db_table': 'internship',
            },
        ),
    ]
