# Generated by Django 4.0.3 on 2022-04-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='phone',
            field=models.PositiveBigIntegerField(blank=True, max_length=12, null=True, verbose_name='Telefon raqam '),
        ),
    ]
