# Generated by Django 4.0.3 on 2022-04-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_alter_intern_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='biography_en',
            field=models.TextField(blank=True, null=True, verbose_name='Amaliyotchi haqida '),
        ),
        migrations.AddField(
            model_name='intern',
            name='biography_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Amaliyotchi haqida '),
        ),
        migrations.AddField(
            model_name='intern',
            name='biography_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Amaliyotchi haqida '),
        ),
        migrations.AddField(
            model_name='intern',
            name='biography_uzb',
            field=models.TextField(blank=True, null=True, verbose_name='Amaliyotchi haqida '),
        ),
        migrations.AddField(
            model_name='intern',
            name='internship_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Amaliyot joyi va muddati '),
        ),
        migrations.AddField(
            model_name='intern',
            name='internship_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Amaliyot joyi va muddati '),
        ),
        migrations.AddField(
            model_name='intern',
            name='internship_uz',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Amaliyot joyi va muddati '),
        ),
        migrations.AddField(
            model_name='intern',
            name='internship_uzb',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Amaliyot joyi va muddati '),
        ),
        migrations.AddField(
            model_name='intern',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name="To'liq ism "),
        ),
        migrations.AddField(
            model_name='intern',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name="To'liq ism "),
        ),
        migrations.AddField(
            model_name='intern',
            name='name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name="To'liq ism "),
        ),
        migrations.AddField(
            model_name='intern',
            name='name_uzb',
            field=models.CharField(max_length=200, null=True, verbose_name="To'liq ism "),
        ),
        migrations.AddField(
            model_name='intern',
            name='position_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Lavozimi '),
        ),
        migrations.AddField(
            model_name='intern',
            name='position_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Lavozimi '),
        ),
        migrations.AddField(
            model_name='intern',
            name='position_uz',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Lavozimi '),
        ),
        migrations.AddField(
            model_name='intern',
            name='position_uzb',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Lavozimi '),
        ),
    ]
