# Generated by Django 4.0.3 on 2022-04-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0004_alter_intern_biography_alter_intern_biography_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='phone',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Telefon raqam: '),
        ),
    ]
