# Generated by Django 4.0.3 on 2022-04-21 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0010_alter_intern_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intern',
            old_name='image',
            new_name='photo',
        ),
    ]
