# Generated by Django 3.2.4 on 2022-05-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0011_rename_image_intern_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tugash vaqti'),
        ),
        migrations.AlterField(
            model_name='intern',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Boshlanish vaqti'),
        ),
    ]
