# Generated by Django 3.2.4 on 2022-05-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0012_auto_20220511_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='internship/images/', verbose_name='Rasm'),
        ),
    ]
