# Generated by Django 4.0.3 on 2022-05-17 06:47

from django.db import migrations, models
import internship.models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0014_internphoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intern',
            options={'verbose_name': 'Yosh olimlar', 'verbose_name_plural': 'Yosh olimlar'},
        ),
        migrations.AlterField(
            model_name='intern',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=internship.models.directory, verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='internphoto',
            name='photo',
            field=models.ImageField(upload_to=internship.models.photos_directory, verbose_name='Foto'),
        ),
    ]
