# Generated by Django 4.0.3 on 2022-04-12 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('name', models.CharField(max_length=500, verbose_name='Nomlanishi')),
                ('name_uz', models.CharField(max_length=500, null=True, verbose_name='Nomlanishi')),
                ('name_uzb', models.CharField(max_length=500, null=True, verbose_name='Nomlanishi')),
                ('name_ru', models.CharField(max_length=500, null=True, verbose_name='Nomlanishi')),
                ('name_en', models.CharField(max_length=500, null=True, verbose_name='Nomlanishi')),
                ('description', models.TextField(verbose_name='Tavsifi')),
                ('description_uz', models.TextField(null=True, verbose_name='Tavsifi')),
                ('description_uzb', models.TextField(null=True, verbose_name='Tavsifi')),
                ('description_ru', models.TextField(null=True, verbose_name='Tavsifi')),
                ('description_en', models.TextField(null=True, verbose_name='Tavsifi')),
                ('region', models.CharField(blank=True, choices=[('andijon', 'Andijon viloyati'), ('buxoro', 'Buxoro viloyati'), ('jizzax', 'Jizzax viloyati'), ('qashqadaryo', 'Qashqadaryo viloyati'), ('navoiy', 'Navoiy viloyati'), ('namangan', 'Namangan viloyati'), ('samarqand', 'Samarqand viloyati'), ('surxondaryo', 'Surxondaryo viloyati'), ('sirdaryo', 'Sirdaryo viloyati'), ('toshkent', 'Toshkent viloyati'), ('fargona', 'Fargʻona viloyati'), ('xorazm', 'Xorazm viloyati'), ('qoraqalpogiston', 'Qoraqalpogʻiston Respublikasi'), ('toshkentsh', 'Toshkent shahar')], max_length=100, null=True, verbose_name='Hududlar')),
                ('cover', models.ImageField(upload_to='images', verbose_name='Tasviri')),
                ('views', models.IntegerField(blank=True, default=0, null=True, verbose_name="Ko'rishlar Soni")),
                ('pub_date', models.DateTimeField(verbose_name='Sanasi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uskuna',
                'verbose_name_plural': 'Uskunalar',
                'db_table': 'equipment',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('name', models.CharField(max_length=150, verbose_name='nomi')),
                ('name_uz', models.CharField(max_length=150, null=True, verbose_name='nomi')),
                ('name_uzb', models.CharField(max_length=150, null=True, verbose_name='nomi')),
                ('name_ru', models.CharField(max_length=150, null=True, verbose_name='nomi')),
                ('name_en', models.CharField(max_length=150, null=True, verbose_name='nomi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uskuna Turi',
                'verbose_name_plural': 'Uskuna Turlari',
                'db_table': 'equipment_type',
            },
        ),
        migrations.CreateModel(
            name='EquipmentImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='EquipmentImages', verbose_name='Foto')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='equipments.equipment', verbose_name='Rasmlar')),
            ],
            options={
                'verbose_name': 'Uskuna Tasviri',
                'verbose_name_plural': 'Uskuna Tasvirlari',
                'db_table': 'equipment_image',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipments.type', verbose_name='Turi'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
