# Generated by Django 4.0.3 on 2022-04-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='pub_date',
            field=models.DateField(verbose_name='Sanasi'),
        ),
    ]
