# Generated by Django 4.0.3 on 2022-04-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0003_alter_equipment_region_alter_equipment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='on_slider',
            field=models.BooleanField(default=False),
        ),
    ]
