# Generated by Django 4.0.3 on 2022-05-07 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0004_equipment_on_slider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='description_en',
            new_name='content_en',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='description_ru',
            new_name='content_ru',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='description_uz',
            new_name='content_uz',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='description_uzb',
            new_name='content_uzb',
        ),
    ]
