# Generated by Django 3.2.4 on 2022-05-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0005_rename_description_equipment_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentimages',
            options={'verbose_name': 'Uskuna rasmi', 'verbose_name_plural': 'Uskuna rasmlari'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Uskuna turi', 'verbose_name_plural': 'Uskuna turlari'},
        ),
        migrations.AlterField(
            model_name='equipment',
            name='cover',
            field=models.ImageField(upload_to='images', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name="Ko'rishlar soni"),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name_uzb',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
    ]
