# Generated by Django 4.0.3 on 2022-04-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opendata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opendata',
            options={'verbose_name': "Ochiq ma'lumot ", 'verbose_name_plural': "Ochiq ma'lumotlar "},
        ),
        migrations.AlterField(
            model_name='opendata',
            name='status',
            field=models.BooleanField(choices=[(True, 'Aktiv'), (False, 'Noaktiv')], default=False),
        ),
    ]
