# Generated by Django 4.0.3 on 2022-04-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opendata', '0002_alter_opendata_options_alter_opendata_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='opendata',
            name='title_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='opendata',
            name='title_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='opendata',
            name='title_uz',
            field=models.CharField(max_length=500, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='opendata',
            name='title_uzb',
            field=models.CharField(max_length=500, null=True, verbose_name='Sarlavha'),
        ),
    ]
