# Generated by Django 4.0.3 on 2022-05-06 05:01

from django.db import migrations, models
import django.db.models.deletion
import opendata.models


class Migration(migrations.Migration):

    dependencies = [
        ('opendata', '0006_alter_opendata_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpendataAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('file', models.FileField(upload_to=opendata.models.directory, verbose_name='Fayl')),
                ('opendata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='opendata.opendata', verbose_name='Fayllar')),
            ],
        ),
    ]
