# Generated by Django 4.0.3 on 2022-05-06 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opendata', '0007_opendataattachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opendata',
            name='status',
        ),
    ]
