# Generated by Django 4.0.3 on 2022-05-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opendata', '0008_remove_opendata_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='opendata',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Matni'),
        ),
    ]
