# Generated by Django 4.0.3 on 2022-05-11 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_menu_type'),
        ('opendata', '0010_opendata_content_en_opendata_content_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opendata',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opendata', to='menu.menu', verbose_name='Menyu'),
        ),
    ]
