# Generated by Django 3.2.4 on 2022-05-11 11:45

from django.db import migrations, models
import opendata.models


class Migration(migrations.Migration):

    dependencies = [
        ('opendata', '0012_opendataattachments_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opendataattachments',
            name='file_en',
            field=models.FileField(null=True, upload_to=opendata.models.directory, verbose_name='Fayl'),
        ),
        migrations.AddField(
            model_name='opendataattachments',
            name='file_ru',
            field=models.FileField(null=True, upload_to=opendata.models.directory, verbose_name='Fayl'),
        ),
        migrations.AddField(
            model_name='opendataattachments',
            name='file_uz',
            field=models.FileField(null=True, upload_to=opendata.models.directory, verbose_name='Fayl'),
        ),
        migrations.AddField(
            model_name='opendataattachments',
            name='file_uzb',
            field=models.FileField(null=True, upload_to=opendata.models.directory, verbose_name='Fayl'),
        ),
    ]
