# Generated by Django 4.0.3 on 2022-05-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opendata', '0013_auto_20220511_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opendata',
            name='content',
        ),
        migrations.RemoveField(
            model_name='opendata',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='opendata',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='opendata',
            name='content_uz',
        ),
        migrations.RemoveField(
            model_name='opendata',
            name='content_uzb',
        ),
        migrations.AddField(
            model_name='opendata',
            name='ilova',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ilova'),
        ),
        migrations.AddField(
            model_name='opendata',
            name='ilova_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ilova'),
        ),
        migrations.AddField(
            model_name='opendata',
            name='ilova_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ilova'),
        ),
        migrations.AddField(
            model_name='opendata',
            name='ilova_uz',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ilova'),
        ),
        migrations.AddField(
            model_name='opendata',
            name='ilova_uzb',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ilova'),
        ),
        migrations.AlterField(
            model_name='opendata',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Havola'),
        ),
    ]
