# Generated by Django 4.0.3 on 2022-05-17 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opendata', '0015_opendata_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opendata',
            options={'ordering': ('index',), 'verbose_name': "Ochiq ma'lumot ", 'verbose_name_plural': "Ochiq ma'lumotlar "},
        ),
    ]
