# Generated by Django 4.0.3 on 2022-05-19 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opendata', '0016_alter_opendata_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='opendata',
            table='open_data',
        ),
    ]
