# Generated by Django 4.0.3 on 2022-04-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Biz haqimizda')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Biz haqimizda')),
                ('description_uzb', models.TextField(blank=True, null=True, verbose_name='Biz haqimizda')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Biz haqimizda')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Biz haqimizda')),
                ('history', models.TextField(blank=True, null=True, verbose_name='Tariximiz')),
                ('history_uz', models.TextField(blank=True, null=True, verbose_name='Tariximiz')),
                ('history_uzb', models.TextField(blank=True, null=True, verbose_name='Tariximiz')),
                ('history_ru', models.TextField(blank=True, null=True, verbose_name='Tariximiz')),
                ('history_en', models.TextField(blank=True, null=True, verbose_name='Tariximiz')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=13, verbose_name='Telefon')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('telegram_url', models.URLField(blank=True, null=True, verbose_name='Telegram')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='Youtube')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Manzil')),
                ('address_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='Manzil')),
                ('address_uzb', models.CharField(blank=True, max_length=200, null=True, verbose_name='Manzil')),
                ('address_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Manzil')),
                ('address_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Manzil')),
                ('transport', models.CharField(blank=True, max_length=200, null=True, verbose_name='Transport')),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, max_length=200, null=True, verbose_name='Uzunlik')),
                ('ltd', models.DecimalField(blank=True, decimal_places=6, max_digits=9, max_length=200, null=True, verbose_name='Kenglik ')),
            ],
            options={
                'verbose_name': 'Biz haqimizda',
                'verbose_name_plural': 'Biz haqimizda',
                'db_table': 'about',
            },
        ),
    ]
