# Generated by Django 4.0.3 on 2022-04-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_transport_en_about_transport_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='phone',
            field=models.CharField(max_length=14, verbose_name='Telefon'),
        ),
    ]
