# Generated by Django 4.0.3 on 2022-05-16 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_about_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='history',
        ),
        migrations.RemoveField(
            model_name='about',
            name='history_en',
        ),
        migrations.RemoveField(
            model_name='about',
            name='history_ru',
        ),
        migrations.RemoveField(
            model_name='about',
            name='history_uz',
        ),
        migrations.RemoveField(
            model_name='about',
            name='history_uzb',
        ),
    ]
