# Generated by Django 4.0.3 on 2022-05-17 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_about_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Jamgʻarma haqida', 'verbose_name_plural': 'Jamgʻarma haqida'},
        ),
    ]
