# Generated by Django 4.0.3 on 2022-05-30 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_alter_about_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about', verbose_name='Foto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('index', models.IntegerField(blank=True, null=True, verbose_name='Tartib raqami')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='about.about', verbose_name='Rasmlar')),
            ],
            options={
                'verbose_name': 'Rasm',
                'verbose_name_plural': 'Rasmlar',
                'db_table': 'about_images',
                'ordering': ['index'],
            },
        ),
    ]
