# Generated by Django 4.0.3 on 2022-04-18 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('name', models.CharField(max_length=255, verbose_name='Mamlakat')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Mamlakat')),
                ('name_uzb', models.CharField(max_length=255, null=True, verbose_name='Mamlakat')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Mamlakat')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Mamlakat')),
                ('code', models.CharField(choices=[('RU', 'Rossiya Federatsiyasi - RU'), ('UZ', 'O‘zbekiston - UZ')], max_length=100, verbose_name='Mamlakatlar kodi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mamlakat',
                'verbose_name_plural': 'Mamlakatlar',
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='ScienceField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('name', models.CharField(max_length=255, verbose_name='Yo‘nalish nomi')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Yo‘nalish nomi')),
                ('name_uzb', models.CharField(max_length=255, null=True, verbose_name='Yo‘nalish nomi')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Yo‘nalish nomi')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Yo‘nalish nomi')),
                ('icon', models.FileField(upload_to='', verbose_name='Logotip')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yo‘nalish',
                'verbose_name_plural': 'Yo‘nalishlar',
                'db_table': 'science_field',
            },
        ),
        migrations.CreateModel(
            name='CountryStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('count', models.SmallIntegerField(verbose_name='Soni')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statisticsapp.country', verbose_name='Mamlakat')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('science_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='statisticsapp.sciencefield', verbose_name='Yo‘nalish')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mamlakat statistikasi',
                'verbose_name_plural': 'Mamlakat statistikalari',
                'db_table': 'country_statistics',
            },
        ),
    ]
