# Generated by Django 4.0.3 on 2022-04-18 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statisticsapp', '0002_remove_countrystatistics_slug_alter_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrystatistics',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='statisticsapp.country', verbose_name='Mamlakat'),
        ),
    ]
