# Generated by Django 4.0.3 on 2022-04-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statisticsapp', '0003_alter_countrystatistics_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrystatistics',
            name='count',
            field=models.BigIntegerField(verbose_name='Soni'),
        ),
    ]
