# Generated by Django 4.0.3 on 2022-04-19 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statisticsapp', '0005_region_regionstatistics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regionstatistics',
            options={'verbose_name': 'Hudud statistikasi', 'verbose_name_plural': 'Hudud statistikalari'},
        ),
        migrations.RemoveField(
            model_name='region',
            name='slug',
        ),
        migrations.AlterField(
            model_name='regionstatistics',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='statisticsapp.region', verbose_name='Hudud'),
        ),
    ]
