# Generated by Django 4.0.3 on 2022-04-19 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statisticsapp', '0006_alter_regionstatistics_options_remove_region_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Hudud', 'verbose_name_plural': 'Hududlar'},
        ),
    ]
