# Generated by Django 4.0.3 on 2022-04-22 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statisticsapp', '0010_financeentity_type_en_financeentity_type_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeentity',
            name='type_en',
        ),
        migrations.RemoveField(
            model_name='financeentity',
            name='type_ru',
        ),
        migrations.RemoveField(
            model_name='financeentity',
            name='type_uz',
        ),
        migrations.RemoveField(
            model_name='financeentity',
            name='type_uzb',
        ),
    ]
