# Generated by Django 4.0.3 on 2022-04-22 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statisticsapp', '0012_alter_financeentity_unique_together_interncount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interncount',
            options={'verbose_name': 'Amaliyotchilar soni', 'verbose_name_plural': 'Amaliyotchilar soni'},
        ),
        migrations.AlterUniqueTogether(
            name='interncount',
            unique_together={('year',)},
        ),
        migrations.AlterModelTable(
            name='interncount',
            table='intern_count',
        ),
    ]
