# Generated by Django 3.2.4 on 2022-04-28 06:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('statisticsapp', '0016_alter_regionsight_options_regionsight_content_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionsight',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
