# Generated by Django 3.2.4 on 2022-04-28 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statisticsapp', '0017_regionsight_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionSightImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/region-sights/images', verbose_name='Rasm')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statisticsapp.regionsight', verbose_name='Sarlavha')),
            ],
            options={
                'verbose_name': 'Rasm',
                'verbose_name_plural': 'Rasmlar',
                'db_table': 'region_sight_images',
            },
        ),
    ]
