# Generated by Django 4.0.3 on 2022-04-29 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statisticsapp', '0018_regionsightimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionsightimages',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='statisticsapp.regionsight', verbose_name='Sarlavha'),
        ),
    ]
