# Generated by Django 3.2.4 on 2022-05-06 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statisticsapp', '0019_alter_regionsightimages_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoungScientistInternship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('scientist', models.PositiveIntegerField(verbose_name='Yosh olimlar soni')),
                ('country', models.PositiveIntegerField(verbose_name='Davlatlar soni')),
                ('field', models.PositiveIntegerField(verbose_name="Yo'nalishlar soni")),
                ('relation', models.PositiveIntegerField(verbose_name='Aloqalar soni')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statisticsapp_youngscientistinternship_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statisticsapp_youngscientistinternship_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Yosh olimlarni ilmiy stajirovkaga yuborish bo'yicha statistik ma'lumot",
                'verbose_name_plural': "Yosh olimlarni ilmiy stajirovkaga yuborish bo'yicha statistik ma'lumotlar",
                'db_table': 'young_scientist_internship',
            },
        ),
    ]
