# Generated by Django 3.2.4 on 2022-05-06 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import statisticsapp.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statisticsapp', '0020_youngscientistinternship'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificInternship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('year', models.PositiveIntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031), (2032, 2032)], default=statisticsapp.models.current_year, verbose_name='Yil')),
                ('region', models.CharField(choices=[('andijon', 'Andijon viloyati'), ('buxoro', 'Buxoro viloyati'), ('jizzax', 'Jizzax viloyati'), ('qashqadaryo', 'Qashqadaryo viloyati'), ('navoiy', 'Navoiy viloyati'), ('namangan', 'Namangan viloyati'), ('samarqand', 'Samarqand viloyati'), ('surxondaryo', 'Surxondaryo viloyati'), ('sirdaryo', 'Sirdaryo viloyati'), ('toshkent', 'Toshkent viloyati'), ('fargona', 'Fargʻona viloyati'), ('xorazm', 'Xorazm viloyati'), ('qoraqalpogiston', 'Qoraqalpogʻiston Respublikasi'), ('toshkentsh', 'Toshkent shahar')], max_length=200, verbose_name='Viloyat')),
                ('successful', models.PositiveIntegerField(verbose_name='Muvaffaqiyatli')),
                ('rejected', models.PositiveIntegerField(verbose_name='Rad etilgan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statisticsapp_scientificinternship_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statisticsapp_scientificinternship_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ilmiy stajirovka',
                'verbose_name_plural': 'Ilmiy stajirovkalar',
                'db_table': 'scientific_internship',
                'unique_together': {('year', 'region')},
            },
        ),
        migrations.CreateModel(
            name='ScientificInternshipStatistic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('amount', models.PositiveBigIntegerField(verbose_name="Mablag'")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statisticsapp_scientificinternshipstatistic_created_by', to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statisticsapp.sciencefield', verbose_name="Yo'nalish")),
                ('scientific_internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statisticsapp.scientificinternship', verbose_name='Ilmiy stajirovka')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statisticsapp_scientificinternshipstatistic_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ilmiy stajirovkalar statistikasi',
                'verbose_name_plural': 'Ilmiy stajirovkalar statistikalari',
                'db_table': 'scientific_internship_statistic',
            },
        ),
    ]
