# Generated by Django 3.2.4 on 2022-05-07 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statisticsapp', '0021_scientificinternship_scientificinternshipstatistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientificinternshipstatistic',
            name='scientific_internship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='statisticsapp.scientificinternship', verbose_name='Ilmiy stajirovka'),
        ),
    ]
