# Generated by Django 3.2.4 on 2022-05-07 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statisticsapp', '0022_alter_scientificinternshipstatistic_scientific_internship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientificinternshipstatistic',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='statisticsapp.sciencefield', verbose_name="Yo'nalish"),
        ),
    ]
