# Generated by Django 3.2.4 on 2022-05-10 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statisticsapp', '0026_annualcost'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='annualcost',
            unique_together={('cost', 'count_type'), ('year', 'count_type')},
        ),
    ]
