# Generated by Django 3.2.4 on 2022-05-10 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statisticsapp', '0028_auto_20220510_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annualcost',
            old_name='count_type',
            new_name='fields',
        ),
    ]
