# Generated by Django 3.2.4 on 2022-05-11 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statisticsapp', '0030_alter_annualcost_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormativeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('date', models.DateField(verbose_name='Sana')),
                ('count', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statisticsapp_normativedocument_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statisticsapp_normativedocument_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Me'yoriy hujjat",
                'verbose_name_plural': "Me'yoriy hujjatlar",
                'db_table': 'normative_documents',
            },
        ),
    ]
