# Generated by Django 3.2.4 on 2022-05-11 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statisticsapp', '0031_normativedocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financeentity',
            options={'verbose_name': "Innovatsion faoliyat sub'yektlarini moliyalashtirish", 'verbose_name_plural': "Innovatsion faoliyat sub'yektlarini moliyalashtirish"},
        ),
    ]
