# Generated by Django 3.2.4 on 2022-05-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statisticsapp', '0032_alter_financeentity_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regionsight',
            options={'verbose_name': 'Mintaqaning diqqatga sazovor joyi', 'verbose_name_plural': 'Mintaqaning diqqatga sazovor joylari'},
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(choices=[('andijon', 'Andijon viloyati'), ('buxoro', 'Buxoro viloyati'), ('jizzax', 'Jizzax viloyati'), ('qashqadaryo', 'Qashqadaryo viloyati'), ('navoiy', 'Navoiy viloyati'), ('namangan', 'Namangan viloyati'), ('samarqand', 'Samarqand viloyati'), ('surxondaryo', 'Surxondaryo viloyati'), ('sirdaryo', 'Sirdaryo viloyati'), ('toshkent', 'Toshkent viloyati'), ('fargona', 'Fargʻona viloyati'), ('xorazm', 'Xorazm viloyati'), ('qoraqalpogiston', 'Qoraqalpogʻiston Respublikasi'), ('toshkentsh', 'Toshkent shahar')], max_length=100, unique=True, verbose_name='Hudud'),
        ),
    ]
