# Generated by Django 4.0.3 on 2022-05-11 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statisticsapp', '0033_alter_normativedocument_created_by_and_more'),
        ('statisticsapp', '0033_auto_20220511_1509'),
    ]

    operations = [
    ]
