# Generated by Django 4.0.3 on 2022-05-12 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statisticsapp', '0035_appealstatistics_appealquarterstatistics_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annualcost',
            options={'ordering': ['year'], 'verbose_name': 'Yillik xarajat', 'verbose_name_plural': "Yillik xarajatlar (turlar bo'yicha)"},
        ),
        migrations.CreateModel(
            name='EquipmentPurchaseStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('title', models.TextField(max_length=500, verbose_name='Qisqacha tavsif')),
                ('title_uz', models.TextField(max_length=500, null=True, verbose_name='Qisqacha tavsif')),
                ('title_uzb', models.TextField(max_length=500, null=True, verbose_name='Qisqacha tavsif')),
                ('title_ru', models.TextField(max_length=500, null=True, verbose_name='Qisqacha tavsif')),
                ('title_en', models.TextField(max_length=500, null=True, verbose_name='Qisqacha tavsif')),
                ('equipment_count', models.PositiveBigIntegerField(verbose_name='Turlar soni')),
                ('invested', models.PositiveBigIntegerField(verbose_name='So‘m yo‘naltirilgan')),
                ('index', models.IntegerField(default=0, verbose_name='Tartib raqami')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Laboratoriya uskunalari statistikasi',
                'verbose_name_plural': 'Laboratoriya uskunalari statistikasi',
                'db_table': 'equipment_purchased',
            },
        ),
    ]
