# Generated by Django 4.0.3 on 2022-05-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statisticsapp', '0037_alter_interncount_options_alter_interncount_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financeentity',
            options={'verbose_name': 'Innovatsion faoliyat subyektlarini moliyalashtirish', 'verbose_name_plural': 'Innovatsion faoliyat subyektlarini moliyalashtirish'},
        ),
        migrations.AlterModelOptions(
            name='interncount',
            options={'verbose_name': 'Amaliyotchilar soni', 'verbose_name_plural': 'Amaliyotchilar soni'},
        ),
        migrations.AlterField(
            model_name='scientificinternship',
            name='region',
            field=models.CharField(choices=[('andijon', 'Andijon viloyati'), ('buxoro', 'Buxoro viloyati'), ('jizzax', 'Jizzax viloyati'), ('qashqadaryo', 'Qashqadaryo viloyati'), ('navoiy', 'Navoiy viloyati'), ('namangan', 'Namangan viloyati'), ('samarqand', 'Samarqand viloyati'), ('surxondaryo', 'Surxondaryo viloyati'), ('sirdaryo', 'Sirdaryo viloyati'), ('toshkent', 'Toshkent viloyati'), ('fargona', 'Fargʻona viloyati'), ('xorazm', 'Xorazm viloyati'), ('qoraqalpogiston', 'Qoraqalpogʻiston Respublikasi'), ('toshkentsh', 'Toshkent shahar')], max_length=200, verbose_name='Hudud'),
        ),
    ]
