# Generated by Django 4.0.3 on 2022-05-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statisticsapp', '0039_alter_sciencefield_options_sciencefield_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annualcost',
            options={'ordering': ['year'], 'verbose_name': 'Asbob-uskunalar', 'verbose_name_plural': "Asbob-uskunalar (turlar bo'yicha)"},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Xorijiy davlatlar', 'verbose_name_plural': 'Xorijiy davlatlar'},
        ),
        migrations.AlterModelOptions(
            name='interncount',
            options={'verbose_name': 'Yosh olimlar yillar kesmida', 'verbose_name_plural': 'Yosh olimlar yillar kesmida'},
        ),
        migrations.AlterModelOptions(
            name='scientificinternship',
            options={'verbose_name': 'Startap loyihalarni moliyalashtirish', 'verbose_name_plural': 'Startap loyihalarni moliyalashtirish'},
        ),
        migrations.AlterModelOptions(
            name='scientificinternshipstatistic',
            options={'verbose_name': 'Startap loyihalarni moliyalashtirish yo‘nalishlar kesmida', 'verbose_name_plural': 'Startap loyihalarni moliyalashtirish yo‘nalishlar kesmida'},
        ),
        migrations.AlterModelOptions(
            name='youngscientistinternship',
            options={'verbose_name': 'Bosh sahifadagi statistika', 'verbose_name_plural': 'Bosh sahifadagi statistika'},
        ),
        migrations.AlterField(
            model_name='scientificinternshipstatistic',
            name='amount',
            field=models.PositiveBigIntegerField(verbose_name='Mablag‘'),
        ),
    ]
