# Generated by Django 4.0.3 on 2022-05-31 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statisticsapp', '0041_financeinternshipyear_financeinternshipstatistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeentity',
            name='type',
            field=models.CharField(choices=[('xorijiy_eksportlar', 'Xorijiy ekspertlar (sohalar kesimida)'), ('noyob_qolyozmalar', 'Noyob qo‘lyozmalar'), ('bazadan_foydalanish', 'Ilmiy-tadqiqot va oliy ta’lim muassasalarining yetakchi elektron ilmiy ma’lumotlar bazalaridan erkin foydalanishni ta’minlash'), ('orolboyi_markazi', 'Ilmiy-tadqiqot va oliy ta’lim muassasalarining xalqaro nashrlarda ilmiy natijalarni chop etishga tayyorlash')], max_length=1000, verbose_name='Turi'),
        ),
        migrations.AlterField(
            model_name='financeinternshipstatistics',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='statisticsapp.financeinternshipyear'),
        ),
    ]
