# Generated by Django 4.0.3 on 2022-04-12 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True, verbose_name='Aktiv')),
                ('title', models.CharField(max_length=500, verbose_name='Nomlanishi')),
                ('title_uz', models.CharField(max_length=500, null=True, verbose_name='Nomlanishi')),
                ('title_uzb', models.CharField(max_length=500, null=True, verbose_name='Nomlanishi')),
                ('title_ru', models.CharField(max_length=500, null=True, verbose_name='Nomlanishi')),
                ('title_en', models.CharField(max_length=500, null=True, verbose_name='Nomlanishi')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='QuyiMenu', to='menu.menu', verbose_name='YuqoriMenyu')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Menyu',
                'verbose_name_plural': 'Menyular',
                'db_table': 'menu',
            },
        ),
    ]
