# Generated by Django 4.0.3 on 2022-04-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menu_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Aktiv'),
        ),
    ]
