# Generated by Django 4.0.3 on 2022-04-12 07:48

from django.db import migrations, models
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_menu_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='type',
            field=models.CharField(choices=[('singlepage', 'Bitta sahifa'), ('post', 'Post'), ('menu', 'Menyu'), ('other', 'Boshqa')], default=menu.models.TypeList['other'], max_length=100, verbose_name='Turi'),
        ),
    ]
