# Generated by Django 4.0.3 on 2022-04-12 07:53

from django.db import migrations, models
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_menu_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Havola'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.CharField(choices=[('singlepage', 'Bitta sahifa'), ('post', 'Post'), ('menu', 'Menyu'), ('photogallery', 'Foto galereya'), ('videogallery', 'Video galereya'), ('equipments', 'Asbob uskunalar'), ('internship', 'Stajirovka'), ('other', 'Boshqa')], default=menu.models.TypeList['other'], max_length=100, verbose_name='Turi'),
        ),
    ]
