# Generated by Django 4.0.3 on 2022-05-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_menu_options_menu_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='note',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Izoh'),
        ),
        migrations.AddField(
            model_name='menu',
            name='note_en',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Izoh'),
        ),
        migrations.AddField(
            model_name='menu',
            name='note_ru',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Izoh'),
        ),
        migrations.AddField(
            model_name='menu',
            name='note_uz',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Izoh'),
        ),
        migrations.AddField(
            model_name='menu',
            name='note_uzb',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Izoh'),
        ),
    ]
