# Generated by Django 4.0.3 on 2022-05-11 05:30

from django.db import migrations, models
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_menu_note_menu_note_en_menu_note_ru_menu_note_uz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.CharField(choices=[('singlepage', 'Bitta sahifa'), ('post', 'Post'), ('attachment', "Ilovali ro'yxat"), ('menu', 'Menyu'), ('photogallery', 'Foto galereya'), ('videogallery', 'Video galereya'), ('equipments', 'Asbob uskunalar'), ('internship', 'Stajirovka'), ('other', 'Boshqa')], default=menu.models.TypeList['other'], max_length=100, verbose_name='Turi'),
        ),
    ]
