# Generated by Django 4.0.3 on 2022-05-17 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_auto_20220511_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['index'], 'verbose_name': 'Menyu', 'verbose_name_plural': 'Menyu'},
        ),
    ]
