# Generated by Django 4.0.3 on 2022-04-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_alter_employee_email_alter_employee_internal_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Aktiv'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Aktiv'),
        ),
        migrations.AddField(
            model_name='supervisoryboard',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Aktiv'),
        ),
    ]
