# Generated by Django 4.0.3 on 2022-04-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0007_alter_department_is_active_alter_employee_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='leadership',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Rahbariyat'),
        ),
    ]
