# Generated by Django 4.0.3 on 2022-04-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0008_employee_leadership'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='responsibilities',
            field=models.TextField(blank=True, null=True, verbose_name='Majburiyatlari'),
        ),
        migrations.AddField(
            model_name='employee',
            name='responsibilities_en',
            field=models.TextField(blank=True, null=True, verbose_name='Majburiyatlari'),
        ),
        migrations.AddField(
            model_name='employee',
            name='responsibilities_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Majburiyatlari'),
        ),
        migrations.AddField(
            model_name='employee',
            name='responsibilities_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Majburiyatlari'),
        ),
        migrations.AddField(
            model_name='employee',
            name='responsibilities_uzb',
            field=models.TextField(blank=True, null=True, verbose_name='Majburiyatlari'),
        ),
        migrations.AddField(
            model_name='employee',
            name='working_hours',
            field=models.CharField(max_length=250, null=True, verbose_name='Qabul vaqtlari'),
        ),
        migrations.AddField(
            model_name='employee',
            name='working_hours_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Qabul vaqtlari'),
        ),
        migrations.AddField(
            model_name='employee',
            name='working_hours_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Qabul vaqtlari'),
        ),
        migrations.AddField(
            model_name='employee',
            name='working_hours_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='Qabul vaqtlari'),
        ),
        migrations.AddField(
            model_name='employee',
            name='working_hours_uzb',
            field=models.CharField(max_length=250, null=True, verbose_name='Qabul vaqtlari'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='Tarjimai holi'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='biography_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tarjimai holi'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='biography_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tarjimai holi'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='biography_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tarjimai holi'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='biography_uzb',
            field=models.TextField(blank=True, null=True, verbose_name='Tarjimai holi'),
        ),
    ]
