# Generated by Django 4.0.3 on 2022-04-21 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0009_employee_responsibilities_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Boʻlim', 'verbose_name_plural': 'Boʻlimlar'},
        ),
    ]
