# Generated by Django 4.0.3 on 2022-04-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0010_alter_department_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['index'], 'verbose_name': 'Hodim', 'verbose_name_plural': 'Hodimlar'},
        ),
        migrations.AddField(
            model_name='employee',
            name='index',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tartib raqami'),
        ),
    ]
