# Generated by Django 3.2.4 on 2022-05-11 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0011_alter_employee_options_employee_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['index'], 'verbose_name': 'Xodim', 'verbose_name_plural': 'Xodimlar'},
        ),
    ]
