# Generated by Django 4.0.3 on 2022-05-17 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0012_alter_employee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supervisoryboard',
            options={'ordering': ['index'], 'verbose_name': 'Kuzatuv kengashi', 'verbose_name_plural': 'Kuzatuv kengashi'},
        ),
    ]
